import Link from "next/link";
import {notFound} from "next/navigation";
import {getServices} from "@/lib/services";
import {areas} from "@/lib/data";
import {isLocale} from "@/lib/i18n";
import {ServiceCards} from "@/components/ServiceCards";
import {JsonLd} from "@/components/JsonLd";
import {APP_URL,BUSINESS} from "@/lib/config";

export default async function Home({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;if(!isLocale(locale))notFound();const es=locale==="es",services=await getServices();
 const steps=es?["Ingresa tu propiedad","Mide tu césped","Recibe tu estimado","Elige tu servicio","Programa tu solicitud"]:["Enter your property","Measure your lawn","Get your estimate","Choose your service","Schedule your request"];
 return <>
 <JsonLd data={{"@context":"https://schema.org","@type":"LocalBusiness",name:BUSINESS.name,url:`${APP_URL}/${locale}`,telephone:BUSINESS.displayPhone,email:BUSINESS.email,areaServed:areas.map(a=>`${a.name}, TX`)}}/>
 <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">{es?"Lawn care local • Central Texas":"Local lawn care • Central Texas"}</div><h1 className="title">{es?"Tu jardín. Bien cuidado. Cada visita.":"Your lawn. Well cared for. Every visit."}</h1><p className="muted" style={{fontSize:"1.18rem",maxWidth:650}}>{es?"Corte de césped, paisajismo y mantenimiento profesional para propietarios que quieren un exterior limpio sin complicaciones.":"Professional mowing, landscaping, and property care for homeowners who want a clean, cared-for yard without the hassle."}</p><div className="actions"><Link className="btn btn-primary" href={`/${locale}/quote`}>{es?"OBTENER COTIZACIÓN GRATIS":"GET MY FREE QUOTE"}</Link><a className="btn btn-light" href={`tel:${BUSINESS.phone}`}>{es?"LLAMAR AHORA":"CALL NOW"}</a></div><div className="trust"><span>✓ {es?"Servicio local":"Local service"}</span><span>✓ {es?"Programación flexible":"Flexible scheduling"}</span><span>✓ {es?"Comunicación directa":"Direct communication"}</span></div></div><div className="hero-art"><div className="hero-note"><div className="eyebrow">{es?"SERVICIO CERCA DE TI":"SERVICE NEAR YOU"}</div><strong>{es?"Cuidamos propiedades en 7 comunidades de Texas":"Serving properties across 7 Texas communities"}</strong><p className="muted">{areas.map(a=>a.name).join(" • ")}</p><Link className="btn btn-primary" href={`/${locale}/service-areas`}>{es?"Ver áreas":"View service areas"}</Link></div></div></div></section>
 <section className="section"><div className="container"><div className="eyebrow">{es?"SERVICIOS PROFESIONALES":"PROFESSIONAL SERVICES"}</div><h2 className="section-title">{es?"Todo lo que tu exterior necesita, en un solo equipo.":"Everything your outdoor space needs, from one local crew."}</h2><p className="muted" style={{maxWidth:700}}>{es?"Mantenimiento recurrente, mejoras de paisaje y cuidado puntual para mantener tu propiedad limpia y presentable.":"Recurring maintenance, landscape improvements, and focused property care designed to keep your yard looking sharp."}</p><ServiceCards services={services.filter(s=>s.featured)} locale={locale}/></div></section>
 <section className="section soft"><div className="container"><div className="eyebrow">{es?"FÁCIL DE EMPEZAR":"SIMPLE FROM THE START"}</div><h2 className="section-title">{es?"Del domicilio a tu solicitud en minutos.":"From your address to a clear request in minutes."}</h2><div className="grid cards steps">{steps.map(x=><div className="card step" key={x}><strong>{x}</strong></div>)}</div></div></section>
 <section className="section"><div className="container cta"><div className="eyebrow" style={{color:"#b7ef35"}}>{es?"COTIZADOR SATELITAL":"SATELLITE QUOTE"}</div><h2 className="section-title">{es?"Mide tu césped. Obtén un estimado. Sin llamadas innecesarias.":"Measure your lawn. Get an estimate. Skip the guesswork."}</h2><p>{es?"Busca tu dirección, marca las áreas de césped y crea una solicitud detallada desde tu teléfono o computadora.":"Find your address, outline your lawn areas, and create a detailed service request from your phone or computer."}</p><Link className="btn btn-accent" href={`/${locale}/quote`}>{es?"MEDIR MI JARDÍN":"MEASURE MY LAWN"}</Link></div></section>
 <section className="section soft"><div className="container"><div className="eyebrow">{es?"POR QUÉ NIETO GREEN CARE":"WHY NIETO GREEN CARE"}</div><h2 className="section-title">{es?"Cuidado local con atención a los detalles.":"Local care with attention to the details."}</h2><div className="grid cards">{(es?[["Servicio confiable","Solicitudes claras y seguimiento humano desde el primer contacto."],["Acabado que se nota","Corte, bordes y limpieza pensados como parte del mismo trabajo."],["Programación sencilla","Opciones únicas y recurrentes adaptadas a las necesidades de tu propiedad."]]:[["Dependable service","Clear requests and human follow-up from the first conversation."],["A finish you notice","Mowing, edging, and cleanup treated as parts of one complete job."],["Easy scheduling","One-time and recurring options designed around your property needs."]]).map(([a,b])=><div className="card" key={a}><div className="eyebrow">✓</div><h3>{a}</h3><p className="muted">{b}</p></div>)}</div></div></section>
 <section className="section"><div className="container"><div className="eyebrow">{es?"ÁREAS DE SERVICIO":"SERVICE AREAS"}</div><h2 className="section-title">{es?"Tu servicio de lawn care local en Central Texas.":"Local lawn care across our Central Texas service area."}</h2>{areas.map(a=><Link className="area" key={a.slug} href={`/${locale}/service-areas/${a.slug}`}><span>{a.name}, TX</span><span>→</span></Link>)}</div></section>
 <section className="section soft"><div className="container empty"><div className="eyebrow">{es?"TRABAJOS REALES":"REAL WORK"}</div><h2>{es?"Una galería reservada para proyectos reales de Nieto Green Care":"A gallery reserved for real Nieto Green Care projects"}</h2><p className="muted">{es?"Aquí aparecerán fotografías aprobadas de trabajos realizados, sin imágenes falsas ni testimonios inventados.":"Approved project photos will appear here as they are published—no fake projects or invented reviews."}</p><Link className="btn btn-primary" href={`/${locale}/gallery`}>{es?"VER GALERÍA":"VIEW GALLERY"}</Link></div></section>
 <section className="section"><div className="container cta"><div className="eyebrow" style={{color:"#b7ef35"}}>{es?"HABLEMOS DE TU PROPIEDAD":"LET'S TALK ABOUT YOUR PROPERTY"}</div><h2 className="section-title">{es?"¿Listo para un jardín mejor cuidado?":"Ready for a better-kept yard?"}</h2><div className="actions"><Link className="btn btn-accent" href={`/${locale}/quote`}>{es?"COTIZAR":"GET A QUOTE"}</Link><a className="btn btn-light" href={`tel:${BUSINESS.phone}`}>{BUSINESS.displayPhone}</a><a className="btn btn-light" href={`sms:${BUSINESS.phone}`}>{es?"ENVIAR MENSAJE":"TEXT US"}</a></div></div></section>
 </>;
}
