"use client";
import dynamic from "next/dynamic";
import {useCallback,useEffect,useState} from "react";
import type {Locale,Service,Frequency} from "@/types";
import type {MapValue} from "./LawnMap";
import {calendarUrl,smsUrl,type BookingSummary} from "@/lib/integrations";
import {BUSINESS} from "@/lib/config";

const LawnMap=dynamic(()=>import("./LawnMap"),{ssr:false,loading:()=> <div className="notice">Loading satellite map…</div>});
type GeoResult={display_name:string;lat:string;lon:string};
type YesNo="yes"|"no"|"";
const emptyGeo:GeoJSON.FeatureCollection={type:"FeatureCollection",features:[]};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);

export function QuoteWizard({locale,services}:{locale:Locale;services:Service[]}){
 const es=locale==="es";
 const [step,setStep]=useState(1),[query,setQuery]=useState(""),[results,setResults]=useState<GeoResult[]>([]),[loading,setLoading]=useState(false),[done,setDone]=useState<BookingSummary|null>(null),[estimate,setEstimate]=useState<number|null>(null),[custom,setCustom]=useState(false);
 const [form,setForm]=useState({address:"",zip:"",lat:0,lng:0,sqft:0,geometry:emptyGeo,service_id:"",frequency:"biweekly" as Frequency,lawn_area:"front_back",corner_lot:"" as YesNo,grass_height:"normal",gate:"" as YesNo,backyard:"" as YesNo,flower_beds:"" as YesNo,pets:"" as YesNo,vinyl_fence:"" as YesNo,above_ground_pool:"" as YesNo,trampoline:"" as YesNo,date:"",time:"",name:"",email:"",phone:"",payment:"cash",notes:"",website:""});
 useEffect(()=>{if(query.trim().length<4||form.address===query)return;const c=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(query)}`,{signal:c.signal});setResults(r.ok?await r.json():[])}finally{setLoading(false)}},600);return()=>{clearTimeout(timer);c.abort()}},[query,form.address]);
 const measure=useCallback((v:MapValue)=>setForm(f=>({...f,sqft:v.sqft,geometry:v.geometry})),[]);
 const selected=services.find(s=>s.id===form.service_id);
 const back=()=>setStep(x=>Math.max(1,x-1));
 const propertyAnswers=`Lawn area: ${form.lawn_area}; Corner lot: ${form.corner_lot}; Grass height: ${form.grass_height}; Gate: ${form.gate}; Backyard: ${form.backyard}; Flower beds: ${form.flower_beds}; Pets: ${form.pets}; Vinyl/plastic fence: ${form.vinyl_fence}; Above-ground pool: ${form.above_ground_pool}; Trampoline: ${form.trampoline}.`;
 async function calculate(){setLoading(true);try{const r=await fetch("/api/quote-estimate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({service_id:form.service_id,lawn_sqft:form.sqft,frequency:form.frequency})});const b=await r.json();if(r.ok){setEstimate(b.estimate??null);setCustom(Boolean(b.custom));setStep(6)}else alert(b.error||"Unable to calculate estimate")}finally{setLoading(false)}}
 async function submit(){setLoading(true);const notes=`${propertyAnswers}\nZIP: ${form.zip}.\n${form.notes}`.trim();const payload={full_name:form.name,email:form.email,phone:form.phone,property_address:form.address,latitude:form.lat,longitude:form.lng,lawn_sqft:form.sqft,lawn_geometry:form.geometry,service_id:form.service_id,requested_date:form.date,requested_time:form.time,frequency:form.frequency,notes,payment_method:form.payment,website:form.website};const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json();setLoading(false);if(!r.ok){alert(body.error||"Unable to save request");return}const summary={name:form.name,service:selected?.name_en||"Service",address:form.address,sqft:form.sqft,estimate:body.estimated_price,date:form.date,time:form.time,frequency:form.frequency,payment:form.payment};setDone(summary);setStep(9)}
 const yn=(key:keyof typeof form,label:string)=><div className="field"><label>{label}</label><div className="actions"><button type="button" className={`btn ${form[key]==="yes"?"btn-primary":"btn-light"}`} onClick={()=>setForm({...form,[key]:"yes"})}>{es?"Sí":"Yes"}</button><button type="button" className={`btn ${form[key]==="no"?"btn-primary":"btn-light"}`} onClick={()=>setForm({...form,[key]:"no"})}>No</button></div></div>;
 if(done&&step===9)return <div className="card"><div className="eyebrow">{es?"Solicitud recibida":"Request received"}</div><h2 className="section-title">{es?"Gracias. Nieto Green Care revisará su solicitud.":"Thank you. Nieto Green Care will review your request."}</h2><p>{es?"La fecha y el precio requieren confirmación final.":"The requested date and estimate require final confirmation."}</p><div className="actions"><a className="btn btn-primary" href={smsUrl(done)}>{es?"Enviar resumen por SMS":"Text request summary"}</a><a className="btn btn-light" target="_blank" rel="noreferrer" href={calendarUrl(done)}>{es?"Añadir recordatorio al calendario":"Add calendar reminder"}</a></div><p className="muted">{BUSINESS.displayPhone}</p></div>;
 return <div className="card"><div className="progress" aria-label={`Step ${step} of 8`}>{[1,2,3,4,5,6,7,8].map(n=><span className={n<=step?"on":""} key={n}/>)}</div>
 {step===1&&<><div className="eyebrow">{es?"Cotización rápida":"Quick quote"}</div><h2>{es?"¿Dónde necesita el servicio?":"Where do you need service?"}</h2><div className="field"><label>{es?"Dirección de la propiedad":"Property address"}</label><input className="input" value={query} onChange={e=>{setQuery(e.target.value);setForm(f=>({...f,address:""}))}} placeholder="123 Main St, Hutto, TX" autoComplete="street-address"/>{loading&&<span>Searching…</span>}{results.map(r=><button type="button" className="input" key={`${r.lat}${r.lon}`} onClick={()=>{setForm(f=>({...f,address:r.display_name,lat:+r.lat,lng:+r.lon}));setQuery(r.display_name);setResults([])}}>{r.display_name}</button>)}</div><div className="field"><label>ZIP Code</label><input className="input" inputMode="numeric" maxLength={5} value={form.zip} onChange={e=>setForm({...form,zip:e.target.value.replace(/\D/g,"").slice(0,5)})} placeholder="78634"/></div></>}
 {step===2&&<><h2>{es?"Configure su servicio":"Build your lawn service"}</h2><div className="field"><label>{es?"Servicio":"Service"}</label><select className="input" value={form.service_id} onChange={e=>setForm({...form,service_id:e.target.value})}><option value="">{es?"Seleccione…":"Select…"}</option>{services.map(s=><option value={s.id} key={s.id}>{es?s.name_es:s.name_en}</option>)}</select></div><div className="field"><label>{es?"Frecuencia":"Frequency"}</label><select className="input" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value as Frequency})}><option value="one_time">{es?"Una vez":"One Time"}</option><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="monthly">Monthly</option></select></div><div className="field"><label>{es?"Área que necesita servicio":"Area to service"}</label><select className="input" value={form.lawn_area} onChange={e=>setForm({...form,lawn_area:e.target.value})}><option value="front_back">{es?"Frente y patio trasero":"Front & Back"}</option><option value="front_only">{es?"Solo frente":"Front Only"}</option><option value="back_only">{es?"Solo patio trasero":"Back Only"}</option></select></div></>}
 {step===3&&<><h2>{es?"Cuéntenos sobre su propiedad":"Tell us about your property"}</h2><p className="muted">{es?"Estas respuestas ayudan a revisar correctamente la cotización.":"These details help us review your quote accurately."}</p>{yn("corner_lot",es?"¿Es un lote de esquina?":"Is this a corner lot?")}<div className="field"><label>{es?"Altura actual del césped":"Current grass height"}</label><select className="input" value={form.grass_height} onChange={e=>setForm({...form,grass_height:e.target.value})}><option value="normal">{es?"Normal / mantenimiento regular":"Normal / regularly maintained"}</option><option value="6_12">6–12 inches</option><option value="over_12">{es?"Más de 12 pulgadas":"Over 12 inches"}</option></select></div>{yn("gate",es?"¿Hay puerta de acceso?":"Is there a gate?")}{yn("backyard",es?"¿Hay patio trasero?":"Is there a backyard?")}{yn("flower_beds",es?"¿Hay jardineras?":"Are there flower beds?")}{yn("pets",es?"¿Hay mascotas en la propiedad?":"Are there pets on the property?")}{yn("vinyl_fence",es?"¿Hay cerca de vinilo o plástico?":"Is there vinyl/plastic fencing?")}{yn("above_ground_pool",es?"¿Hay piscina elevada?":"Is there an above-ground pool?")}{yn("trampoline",es?"¿Hay trampolín?":"Is there a trampoline?")}</>}
 {step===4&&<><h2>{es?"Mida el césped desde el satélite":"Measure your lawn by satellite"}</h2><p className="muted">{es?"Marque únicamente las áreas que desea que atendamos.":"Outline only the lawn areas you want serviced."}</p>{form.lat?<LawnMap lat={form.lat} lng={form.lng} onChange={measure}/>:<p>{es?"Seleccione una dirección primero.":"Select an address first."}</p>}<div className="notice"><strong>{es?"ÁREA TOTAL":"TOTAL LAWN AREA"}</strong><br/>{Math.round(form.sqft).toLocaleString()} SQ FT</div></>}
 {step===5&&<><h2>{es?"¿Cuándo prefiere el servicio?":"When would you like service?"}</h2><div className="grid cards"><div className="field"><label>Date</label><input type="date" min={new Date().toISOString().slice(0,10)} className="input" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div><div className="field"><label>{es?"Hora preferida":"Preferred time"}</label><input type="time" className="input" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></div></div><p className="muted">{es?"La disponibilidad final será confirmada por Nieto Green Care.":"Final availability will be confirmed by Nieto Green Care."}</p></>}
 {step===6&&<><div className="eyebrow">{es?"Su plan":"Your lawn plan"}</div><h2>{es?"Cotización de Nieto Green Care":"Your Nieto Green Care Lawn Plan"}</h2><div className="notice"><strong style={{fontSize:"2rem"}}>{custom||estimate===null?(es?"Cotización personalizada":"Custom Quote"):money(estimate)}</strong><br/><span>{es?"Estimación sujeta a revisión final":"Estimate subject to final review"}</span></div><dl><dt>{es?"Área":"Lawn area"}</dt><dd>{Math.round(form.sqft).toLocaleString()} sq ft</dd><dt>{es?"Frecuencia":"Frequency"}</dt><dd>{form.frequency}</dd><dt>{es?"Zona":"Service area"}</dt><dd>{form.lawn_area.replaceAll("_"," ")}</dd><dt>{es?"Fecha solicitada":"Requested date"}</dt><dd>{form.date} {form.time}</dd></dl></>}
 {step===7&&<><h2>{es?"¿A quién contactamos?":"Who should we contact?"}</h2><input aria-hidden="true" tabIndex={-1} autoComplete="off" style={{position:"absolute",left:"-9999px"}} value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/>{[["name",es?"Nombre completo":"Full name","text"],["email","Email","email"],["phone",es?"Teléfono":"Phone","tel"]].map(([k,l,t])=><div className="field" key={k}><label>{l}</label><input required type={t} className="input" value={form[k as keyof typeof form] as string} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="field"><label>{es?"Preferencia de pago":"Payment preference"}</label><select className="input" value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}><option value="cash">Cash</option><option value="transfer">Transfer</option></select></div><div className="field"><label>{es?"Detalles adicionales":"Anything else we should know?"}</label><textarea className="input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></>}
 {step===8&&<><h2>{es?"Revise y envíe su solicitud":"Review & request service"}</h2><dl><dt>Address</dt><dd>{form.address}, {form.zip}</dd><dt>Service</dt><dd>{selected?es?selected.name_es:selected.name_en:"—"}</dd><dt>Lawn size</dt><dd>{Math.round(form.sqft).toLocaleString()} sq ft</dd><dt>Frequency</dt><dd>{form.frequency}</dd><dt>Estimate</dt><dd>{custom||estimate===null?(es?"Cotización personalizada":"Custom Quote"):money(estimate)}</dd><dt>Date / Time</dt><dd>{form.date} {form.time}</dd><dt>Payment</dt><dd>{form.payment}</dd></dl><p className="notice">{es?"Enviar esta solicitud no confirma automáticamente la cita ni el precio final.":"Submitting this request does not automatically confirm the appointment or final price."}</p></>}
 <div className="actions" style={{marginTop:"2rem"}}>{step>1&&<button type="button" className="btn btn-light" onClick={back}>{es?"Atrás":"Back"}</button>}{step===1&&<button type="button" className="btn btn-primary" disabled={!form.address||form.zip.length!==5} onClick={()=>setStep(2)}>{es?"Continuar":"Continue"}</button>}{step===2&&<button type="button" className="btn btn-primary" disabled={!form.service_id} onClick={()=>setStep(3)}>{es?"Continuar":"Continue"}</button>}{step===3&&<button type="button" className="btn btn-primary" disabled={!form.corner_lot||!form.gate||!form.backyard||!form.flower_beds||!form.pets||!form.vinyl_fence||!form.above_ground_pool||!form.trampoline} onClick={()=>setStep(4)}>{es?"Continuar":"Continue"}</button>}{step===4&&<button type="button" className="btn btn-primary" disabled={!form.sqft} onClick={()=>setStep(5)}>{es?"Continuar":"Continue"}</button>}{step===5&&<button type="button" className="btn btn-primary" disabled={!form.date||!form.time||loading} onClick={calculate}>{loading?(es?"Calculando…":"Calculating…"):(es?"Ver mi cotización":"See My Quote")}</button>}{step===6&&<button type="button" className="btn btn-primary" onClick={()=>setStep(7)}>{es?"Continuar":"Continue"}</button>}{step===7&&<button type="button" className="btn btn-primary" disabled={!form.name.trim()||!form.email.trim()||!form.phone.trim()} onClick={()=>setStep(8)}>{es?"Revisar solicitud":"Review Request"}</button>}{step===8&&<button type="button" className="btn btn-primary" disabled={loading} onClick={submit}>{loading?(es?"Enviando…":"Sending…"):(es?"SOLICITAR SERVICIO":"REQUEST SERVICE")}</button>}</div>
 </div>
}
